quartz:
  enabled: true
server:
  port: 9090
spring:
  application:
    name: Spring-Quartz-Scheduler                                       #Quartz调度中心
  datasource:
    url: jdbc:mysql://localhost:3306/wish_bottle?characterEncoding=utf8
    username: root
    password: root
    tomcat:
      initialSize: 20
      maxActive: 100
      maxIdle: 100
      minIdle: 20
      maxWait: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
    schema: classpath:job_entity.sql, classpath:quartz_innodb.sql
    initialization-mode: always
